- name: Menjalankan docker tazkia
  hosts: btj-academy
  become: true
  tasks:
   - name: copy Dockerfile
     ansible.builtin.copy:
      src: /home/tazkiaatharizadhivara/btj-academy-tazkia/Dockerfile
      dest: btj-academy-tazkia
     become: true
   - name: copy app.py
     ansible.builtin.copy:
      src: /home/tazkiaatharizadhivara/btj-academy-tazkia/app.py
      dest: btj-academy-tazkia
     become: true
   - name: copy requirements.txt
     ansible.builtin.copy:
      src: /home/tazkiaatharizadhivara/btj-academy-tazkia/requirements.txt
      dest: btj-academy-tazkia
     become: true
   - name: build docker image
     ansible.builtin.command:
      cmd: 'docker build -t app-flask:0.1.0 btj-academy-tazkia'
   - name: run docker container
     ansible.builtin.command:
      cmd: 'docker run -it -d --name tazkia-flask -p 8099:8099 app-flask:0.1.0'